### ISSUE TITLE
Support for Editions

### ISSUE THREAD

**Issue by Frzk** [Scalingo/sonarqube-buildpack#11]
SonarQube has multiple editions: `Community`, `Developer`, `Enterprise` and `Data Center`.

Currently, the buildpack only supports the `Community` edition.
Let's support all of them via a `SONARQUBE_EDITION` environment variable that defaults to `community`.

**Comment by Soulou** [comment]
I assume that there are some license issues for some versions and that all are not necessarily deployable on Scalingo. (Wondering what is the Data Center version, not sure it runs on a PaaS here)

**Comment by Frzk** [comment]
The features are described here: https://www.sonarsource.com/products/sonarqube/downloads/

Should I close and update the doc to clearly state we only support 'Community'? 'Community'+'Developer'?..
